apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # Change from LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000  # Must match your container's port